<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Icons\favicon(2).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\arch.png" />
    <None Remove="Assets\Images\chromeos.png" />
    <None Remove="Assets\Images\endeavouros.png" />
    <None Remove="Assets\Images\fedora.png" />
    <None Remove="Assets\Images\kali.png" />
    <None Remove="Assets\Images\kubuntu.png" />
    <None Remove="Assets\Images\manjaro.png" />
    <None Remove="Assets\Images\mint.png" />
    <None Remove="Assets\Images\Mint\Mint1.png" />
    <None Remove="Assets\Images\Mint\mint2.png" />
    <None Remove="Assets\Images\popos.png" />
    <None Remove="Assets\Images\Ubuntu.png" />
    <None Remove="Assets\Images\Ubuntu\ubuntu1.jpg" />
    <None Remove="Assets\Images\Ubuntu\ubuntu2.png" />
    <None Remove="Assets\Images\xubuntu.png" />
    <None Remove="Assets\Images\zorin.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Icons\favicon(2).ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="Helpers\" />
    <Folder Include="Services\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\arch.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\chromeos.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\endeavouros.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\fedora.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\kali.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\kubuntu.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\manjaro.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\mint.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Mint\Mint1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Mint\mint2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\popos.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Ubuntu.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Ubuntu\ubuntu1.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\Ubuntu\ubuntu2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\xubuntu.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\zorin.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
